// import Navbar from "@/components/Navbar";
import "./globals.css";
import Footer from "@/components/Footer";
import Navbar1 from "@/components/navbar/Navbar1";
import ReduxProvider from "./providers/ReduxProvider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ReduxProvider>
      <html lang="en">
        <body
          className="bg-lightBackground text-primary"
        >
          <Navbar1 />
          {children}
          <Footer />
        </body>
      </html>
    </ReduxProvider>
  );
}
